name: Docker Image CI

on:
  push:
    tags:
      - 'v*.*.*'  

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Docker
        uses: docker/setup-buildx-action@v2

      - name: Login no Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Construir e taguear a imagem Docker
        env:
          VERSION: ${{ github.ref_name }} 
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/meuapp:${{ env.VERSION }} .
          docker tag ${{ secrets.DOCKER_USERNAME }}/meuapp:${{ env.VERSION }} ${{ secrets.DOCKER_USERNAME }}/meuapp:latest

      - name: Fazer push da imagem para o Docker Hub
        run: |
          docker push ${{ secrets.DOCKER_USERNAME }}/meuapp:${{ env.VERSION }}
          docker push ${{ secrets.DOCKER_USERNAME }}/meuapp:latest
