name: Gatilho manual

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Criar um arquivo de exemplo
        run: echo "Hello, Artefato!" > artefato.txt

      - name: Fazer upload do artefato
        uses: actions/upload-artifact@v4
        with:
          name: meu-artefato
          path: artefato.txt

