name: Test application

on:
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14, 16, 17, 20, 21]

    steps:
      - uses: actions/checkout@v2

      - name: Configurar ambiente
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Cypress
        run: npm install cypress -g

      - name: Install and Run
        run: |
          npm install
          npm run dev

      - name: Testar
        run: cypress run
