name: Test application

on: [push]
  

jobs:
     build:
        runs-on: ubuntu-latest
        steps:
         - uses: actions/checkout@v2
            
         - name: Configurar ambiente
           uses: actions/setup-node@v3
           with:
            node-version: '21'           
           
        
         - name: Install Cypress
           run: npm install cypress -g

         - name: Install
           run: npm install && npm run dev &

         - name: Testar
           run: cypress run