name: Python application

on: [push]

jobs:
     build:
        runs-on: ubuntu-latest
        steps:
         - uses: actions/checkout@v2
            
         - name: Configurar ambiente
           uses: actions/setup-node@v3
        
         - name: Install
           run: npm install

         - name: Testar
           run: npm run cypress:run