name: Multicloud deploy pipeline

on:
  push:
    branches: ["master"]

jobs:
    deploy:
        runs-on: ubuntu-latest
        environment: Production
       
        steps:
            - uses: actions/checkout@v4

            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@v1.1.0
              with:
                host: ${{ secrets.EC2_HOST }}
                username:  ${{ secrets.EC2_USERNAME }}
                password: ${{ secrets.EC2_PRIVATE_KEY }}
                port: 22
                script: whoami

