name: Multicloud deploy pipeline

on:
  push:
    branches: ["master"]

concurrency: 
  cancel-in-progress: true
  group: deploy_${{github.ref}}

jobs:
      tests:
        uses: oseiasal/fipe_historico/.github/workflows/pull_request.yml@master

      deploy:
        needs: [tests]
        runs-on: ubuntu-latest
        environment: Production
                
        steps:
            - uses: actions/checkout@v4

            - name: executing remote ssh commands using password
              uses: appleboy/ssh-action@v1.1.0
              with:
                host: ${{ secrets.EC2_HOST }}
                username:  ${{ secrets.EC2_USERNAME }}
                key: ${{ secrets.EC2_PRIVATE_KEY }}
                port: 22
                script: ./setup.sh

